/**
 * 样例航次。航段距离为演示值。货物物性取自公开 MSDS/IBC 资料,USCG 族按
 * shared/uscg-compatibility-data.ts 核对;样船为合成数据。
 */
import type { StowVoyage } from "./types";

export const SAMPLE_VOYAGE: StowVoyage = {
  shipId: "sample-mr",
  voyageNo: "SAMPLE-2026-01",
  calls: [
    { id: "L1", seq: 0, port: "蔚山", berth: "3 号泊位" },
    { distanceNm: 2, id: "L2", seq: 1, port: "蔚山", berth: "7 号泊位" },
    { distanceNm: 10600, id: "D1", seq: 2, port: "鹿特丹", berth: "Botlek", maxDraftM: 12.3, waterDensity: 1 },
    { distanceNm: 90, id: "D2", seq: 3, port: "安特卫普", berth: "K1", maxDraftM: 12.5, waterDensity: 1.025 },
    { distanceNm: 2, id: "D3", seq: 4, port: "安特卫普", berth: "K4" },
  ],
  parcels: [
    {
      id: "meoh",
      productId: null,
      name: "METHANOL",
      display: "甲醇 Methanol",
      group: 20,
      quantityMt: 12000,
      density: 0.79,
      loadCallId: "L1",
      dischargeCallId: "D1",
      heating: { enabled: false },
      boilPointC: 64.7,
      meltPointC: -97.6,
      polymerizable: false,
      maxAllowedTempC: null,
    },
    {
      id: "naoh",
      productId: null,
      name: "SODIUM HYDROXIDE SOLUTION",
      display: "烧碱溶液 50%",
      group: 5,
      quantityMt: 8000,
      density: 1.52,
      loadCallId: "L1",
      dischargeCallId: "D2",
      heating: { enabled: false },
      boilPointC: 140,
      meltPointC: 12,
      polymerizable: false,
      maxAllowedTempC: null,
    },
    {
      id: "phenol",
      productId: null,
      name: "PHENOL",
      display: "苯酚(熔融)Phenol",
      group: 21,
      quantityMt: 5000,
      density: 1.05,
      loadCallId: "L2",
      dischargeCallId: "D3",
      heating: { enabled: true, carriageTempC: 50 },
      boilPointC: 181.7,
      meltPointC: 40.9,
      polymerizable: false,
      maxAllowedTempC: null,
    },
    {
      id: "acn",
      productId: null,
      name: "ACRYLONITRILE",
      display: "丙烯腈 Acrylonitrile",
      group: 15,
      quantityMt: 4000,
      density: 0.81,
      loadCallId: "L2",
      dischargeCallId: "D1",
      heating: { enabled: false },
      boilPointC: 77.3,
      meltPointC: -83.5,
      polymerizable: true,
      maxAllowedTempC: null,
    },
    {
      id: "meg1",
      productId: null,
      name: "ETHYLENE GLYCOL",
      display: "乙二醇 MEG(鹿特丹)",
      group: 20,
      quantityMt: 6000,
      density: 1.11,
      loadCallId: "L1",
      dischargeCallId: "D1",
      heating: { enabled: false },
      boilPointC: 197.3,
      meltPointC: -13,
      polymerizable: false,
      maxAllowedTempC: null,
    },
    {
      id: "meg2",
      productId: null,
      name: "ETHYLENE GLYCOL",
      display: "乙二醇 MEG(安特卫普)",
      group: 20,
      quantityMt: 5000,
      density: 1.11,
      loadCallId: "L1",
      dischargeCallId: "D2",
      heating: { enabled: false },
      boilPointC: 197.3,
      meltPointC: -13,
      polymerizable: false,
      maxAllowedTempC: null,
    },
  ],
};
